#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         3
bspc config window_gap          7
bspc config focused_border_color "#005577"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Spotify desktop=^8
bspc rule -a discord desktop=^8

~/.config/polybar/launch.sh &
feh --bg-scale ~/.config/bspwm/wallpapers/wp4.jpg
